version: "3.9"

services:
  database:
    image: postgres:alpine
    container_name: database_postgres
    restart: always
    ports:
      - 5433:5433
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - pgdata:/data/postgres

volumes:
  pgdata:
    driver: local
